// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart'; // .env paketimizi buraya ekledik!

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Sızmayı önlemek için 'const' kelimelerini 'static' yaptık ve apiKey'leri kasaya bağladık!
  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZK78zZubh+xAY\nLfn6e3yri6Kojg+XZFYSrSeb0pdTGpc+nsptg4P6T8cEM3lyVzE9NLY3yZfWiu6S\nrGn1WJ+tMwfbWWfOKadxB9aChVlhSMnBqzN5VyoCYf4NEmUqt4/7sQJ186xl4VCv\nWLVFGWRXEdClgcyZfVFsyqBj7FZG7SrJ4zT5L05PQuEoY5+VjOrs7rERNO/PGDtE\n7bV6/mY3eW8MU8YLVY/ZULITN3XkSXYbEpEJZQjQz8sYWaDLLe5aWgVGOQ2h02P+\nK+BgSXlmJ2YksYkElAcqNBFN3q88OxuBmHQQZKAcqz+wiyZHL+YDO0ee6Xv8g3yC\nl6UT/zs5AgMBAAECggEAD5xLCArWgJUFGqXC6qGfvt8EFKAn3CLUd+JQXVvs4sIc\nxHvL/zXOY1oymw3A9KOIx+dho9VmpW2y611pjiD6Yx1GkXcu8m7B2y30kYhUJ+tS\nbqvLWvREeoowqXXkvCIJqVnsuYc8XITGY5yLmu9/z7Tn2hpctw7z173d81kgoOk+\nHE1WePtLnSUotMvci6T28tdBWeYOGIudTRgOeNNwFCs8rkmXYw1NqmeHDhb2onAR\noH8b+jxziT2RoPRsjTo9Rt3fkdN9AfVQ3QNexuBWYA9pPN+sqJ9ugBMqOYKdfwpz\ntgtZ8XcSXp5J4KFQyqQGsgqrbUdtbZEhMpQ2xqcwRQKBgQDG72XGHrr/Y4FjIxdA\nO1T2ncSGVvSkYPQ503+xJUkWH27yCsqCp7sBksqzveWtVTqbdNkZpcRWh7F+p8VX\nfBn2EsiOCNOTtE2IwDpAOzCb7PaCO/iK3B7NgYg2gGCT38ZmqLO/I3G8tU1iBKPU\n7tO/znGbxoIYTL+okBNH5Q7f7QKBgQDFG7JmoSADNPhpczW6FVV0F22xYFQXUed9\n/Yq9sR0UPb5HjqEHfyKGPOVQ4IFx4nX2bL47/y7pDGm0JNd+YJeYr7Le6wctbYjQ\ngdeIUJg6Ve2arsi+hdIULwqvXHX9oc/Pqsra7zqMVdDs+hgcowAfCUz2v8Y7mwvw\n24iOjfHm/QKBgCuCpOHmSsQdAWmrfSRhVb3y188CKdPiGMilB6K5IvkhuuRZk91r\nzi0T7B3QBPIaWA00S1+esAi0+Q9YpoLx88OsbA0UxSHjJ6onURZHW+ReubPWZhAJ\nAPu1vxMclQMCyKQfdeDyYagCh4BOv36NFec3wgVuL3odHzZA/NaWtOApAoGAWZAb\nQT0Hgc2I7sl16UcWXDjlFAsUSsBhssMJTuZysybXFka97t0a/+odvOE2kFv5g+6n\nhjWOyEBmq39uF7OmTq/PVDFxQngaCbxmBj+w3Bj9bSLsfn3qFlfFwCcASi5DcjZG\nFLNNZET+OR/u4txCCtg8C4baeW0bQOdQJo5jE7UCgYEAm3P4Z/KCNc8CcbF2IJAX\nj6eklvHWXwq3U/ZkizJ4N8khdhVHEtfleUeTBWJWvlG8p2HORz21Yx9QwZouQ92K\ntZq8Lep7lTxkFRzJ92ozKRa/0hfAtYBeCSUyWvBahM9AtwQro4JeF4VUq8iWO784\nslbAEm9kzJhmizdweCZPN1k'] ?? '',
    appId: '1:496830271833:web:5125cde5e96771fc44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    authDomain: 'medtime-7adda.firebaseapp.com',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    measurementId: 'G-DXN8L9K035',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZK78zZubh+xAY\nLfn6e3yri6Kojg+XZFYSrSeb0pdTGpc+nsptg4P6T8cEM3lyVzE9NLY3yZfWiu6S\nrGn1WJ+tMwfbWWfOKadxB9aChVlhSMnBqzN5VyoCYf4NEmUqt4/7sQJ186xl4VCv\nWLVFGWRXEdClgcyZfVFsyqBj7FZG7SrJ4zT5L05PQuEoY5+VjOrs7rERNO/PGDtE\n7bV6/mY3eW8MU8YLVY/ZULITN3XkSXYbEpEJZQjQz8sYWaDLLe5aWgVGOQ2h02P+\nK+BgSXlmJ2YksYkElAcqNBFN3q88OxuBmHQQZKAcqz+wiyZHL+YDO0ee6Xv8g3yC\nl6UT/zs5AgMBAAECggEAD5xLCArWgJUFGqXC6qGfvt8EFKAn3CLUd+JQXVvs4sIc\nxHvL/zXOY1oymw3A9KOIx+dho9VmpW2y611pjiD6Yx1GkXcu8m7B2y30kYhUJ+tS\nbqvLWvREeoowqXXkvCIJqVnsuYc8XITGY5yLmu9/z7Tn2hpctw7z173d81kgoOk+\nHE1WePtLnSUotMvci6T28tdBWeYOGIudTRgOeNNwFCs8rkmXYw1NqmeHDhb2onAR\noH8b+jxziT2RoPRsjTo9Rt3fkdN9AfVQ3QNexuBWYA9pPN+sqJ9ugBMqOYKdfwpz\ntgtZ8XcSXp5J4KFQyqQGsgqrbUdtbZEhMpQ2xqcwRQKBgQDG72XGHrr/Y4FjIxdA\nO1T2ncSGVvSkYPQ503+xJUkWH27yCsqCp7sBksqzveWtVTqbdNkZpcRWh7F+p8VX\nfBn2EsiOCNOTtE2IwDpAOzCb7PaCO/iK3B7NgYg2gGCT38ZmqLO/I3G8tU1iBKPU\n7tO/znGbxoIYTL+okBNH5Q7f7QKBgQDFG7JmoSADNPhpczW6FVV0F22xYFQXUed9\n/Yq9sR0UPb5HjqEHfyKGPOVQ4IFx4nX2bL47/y7pDGm0JNd+YJeYr7Le6wctbYjQ\ngdeIUJg6Ve2arsi+hdIULwqvXHX9oc/Pqsra7zqMVdDs+hgcowAfCUz2v8Y7mwvw\n24iOjfHm/QKBgCuCpOHmSsQdAWmrfSRhVb3y188CKdPiGMilB6K5IvkhuuRZk91r\nzi0T7B3QBPIaWA00S1+esAi0+Q9YpoLx88OsbA0UxSHjJ6onURZHW+ReubPWZhAJ\nAPu1vxMclQMCyKQfdeDyYagCh4BOv36NFec3wgVuL3odHzZA/NaWtOApAoGAWZAb\nQT0Hgc2I7sl16UcWXDjlFAsUSsBhssMJTuZysybXFka97t0a/+odvOE2kFv5g+6n\nhjWOyEBmq39uF7OmTq/PVDFxQngaCbxmBj+w3Bj9bSLsfn3qFlfFwCcASi5DcjZG\nFLNNZET+OR/u4txCCtg8C4baeW0bQOdQJo5jE7UCgYEAm3P4Z/KCNc8CcbF2IJAX\nj6eklvHWXwq3U/ZkizJ4N8khdhVHEtfleUeTBWJWvlG8p2HORz21Yx9QwZouQ92K\ntZq8Lep7lTxkFRzJ92ozKRa/0hfAtYBeCSUyWvBahM9AtwQro4JeF4VUq8iWO784\nslbAEm9kzJhmizdweCZPN1k'] ?? '',
    appId: '1:496830271833:android:053df3ed26945dcc44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZK78zZubh+xAY\nLfn6e3yri6Kojg+XZFYSrSeb0pdTGpc+nsptg4P6T8cEM3lyVzE9NLY3yZfWiu6S\nrGn1WJ+tMwfbWWfOKadxB9aChVlhSMnBqzN5VyoCYf4NEmUqt4/7sQJ186xl4VCv\nWLVFGWRXEdClgcyZfVFsyqBj7FZG7SrJ4zT5L05PQuEoY5+VjOrs7rERNO/PGDtE\n7bV6/mY3eW8MU8YLVY/ZULITN3XkSXYbEpEJZQjQz8sYWaDLLe5aWgVGOQ2h02P+\nK+BgSXlmJ2YksYkElAcqNBFN3q88OxuBmHQQZKAcqz+wiyZHL+YDO0ee6Xv8g3yC\nl6UT/zs5AgMBAAECggEAD5xLCArWgJUFGqXC6qGfvt8EFKAn3CLUd+JQXVvs4sIc\nxHvL/zXOY1oymw3A9KOIx+dho9VmpW2y611pjiD6Yx1GkXcu8m7B2y30kYhUJ+tS\nbqvLWvREeoowqXXkvCIJqVnsuYc8XITGY5yLmu9/z7Tn2hpctw7z173d81kgoOk+\nHE1WePtLnSUotMvci6T28tdBWeYOGIudTRgOeNNwFCs8rkmXYw1NqmeHDhb2onAR\noH8b+jxziT2RoPRsjTo9Rt3fkdN9AfVQ3QNexuBWYA9pPN+sqJ9ugBMqOYKdfwpz\ntgtZ8XcSXp5J4KFQyqQGsgqrbUdtbZEhMpQ2xqcwRQKBgQDG72XGHrr/Y4FjIxdA\nO1T2ncSGVvSkYPQ503+xJUkWH27yCsqCp7sBksqzveWtVTqbdNkZpcRWh7F+p8VX\nfBn2EsiOCNOTtE2IwDpAOzCb7PaCO/iK3B7NgYg2gGCT38ZmqLO/I3G8tU1iBKPU\n7tO/znGbxoIYTL+okBNH5Q7f7QKBgQDFG7JmoSADNPhpczW6FVV0F22xYFQXUed9\n/Yq9sR0UPb5HjqEHfyKGPOVQ4IFx4nX2bL47/y7pDGm0JNd+YJeYr7Le6wctbYjQ\ngdeIUJg6Ve2arsi+hdIULwqvXHX9oc/Pqsra7zqMVdDs+hgcowAfCUz2v8Y7mwvw\n24iOjfHm/QKBgCuCpOHmSsQdAWmrfSRhVb3y188CKdPiGMilB6K5IvkhuuRZk91r\nzi0T7B3QBPIaWA00S1+esAi0+Q9YpoLx88OsbA0UxSHjJ6onURZHW+ReubPWZhAJ\nAPu1vxMclQMCyKQfdeDyYagCh4BOv36NFec3wgVuL3odHzZA/NaWtOApAoGAWZAb\nQT0Hgc2I7sl16UcWXDjlFAsUSsBhssMJTuZysybXFka97t0a/+odvOE2kFv5g+6n\nhjWOyEBmq39uF7OmTq/PVDFxQngaCbxmBj+w3Bj9bSLsfn3qFlfFwCcASi5DcjZG\nFLNNZET+OR/u4txCCtg8C4baeW0bQOdQJo5jE7UCgYEAm3P4Z/KCNc8CcbF2IJAX\nj6eklvHWXwq3U/ZkizJ4N8khdhVHEtfleUeTBWJWvlG8p2HORz21Yx9QwZouQ92K\ntZq8Lep7lTxkFRzJ92ozKRa/0hfAtYBeCSUyWvBahM9AtwQro4JeF4VUq8iWO784\nslbAEm9kzJhmizdweCZPN1k'] ?? '',
    appId: '1:496830271833:ios:bf3ece156f5d78fe44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    iosBundleId: 'com.example.medtime',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZK78zZubh+xAY\nLfn6e3yri6Kojg+XZFYSrSeb0pdTGpc+nsptg4P6T8cEM3lyVzE9NLY3yZfWiu6S\nrGn1WJ+tMwfbWWfOKadxB9aChVlhSMnBqzN5VyoCYf4NEmUqt4/7sQJ186xl4VCv\nWLVFGWRXEdClgcyZfVFsyqBj7FZG7SrJ4zT5L05PQuEoY5+VjOrs7rERNO/PGDtE\n7bV6/mY3eW8MU8YLVY/ZULITN3XkSXYbEpEJZQjQz8sYWaDLLe5aWgVGOQ2h02P+\nK+BgSXlmJ2YksYkElAcqNBFN3q88OxuBmHQQZKAcqz+wiyZHL+YDO0ee6Xv8g3yC\nl6UT/zs5AgMBAAECggEAD5xLCArWgJUFGqXC6qGfvt8EFKAn3CLUd+JQXVvs4sIc\nxHvL/zXOY1oymw3A9KOIx+dho9VmpW2y611pjiD6Yx1GkXcu8m7B2y30kYhUJ+tS\nbqvLWvREeoowqXXkvCIJqVnsuYc8XITGY5yLmu9/z7Tn2hpctw7z173d81kgoOk+\nHE1WePtLnSUotMvci6T28tdBWeYOGIudTRgOeNNwFCs8rkmXYw1NqmeHDhb2onAR\noH8b+jxziT2RoPRsjTo9Rt3fkdN9AfVQ3QNexuBWYA9pPN+sqJ9ugBMqOYKdfwpz\ntgtZ8XcSXp5J4KFQyqQGsgqrbUdtbZEhMpQ2xqcwRQKBgQDG72XGHrr/Y4FjIxdA\nO1T2ncSGVvSkYPQ503+xJUkWH27yCsqCp7sBksqzveWtVTqbdNkZpcRWh7F+p8VX\nfBn2EsiOCNOTtE2IwDpAOzCb7PaCO/iK3B7NgYg2gGCT38ZmqLO/I3G8tU1iBKPU\n7tO/znGbxoIYTL+okBNH5Q7f7QKBgQDFG7JmoSADNPhpczW6FVV0F22xYFQXUed9\n/Yq9sR0UPb5HjqEHfyKGPOVQ4IFx4nX2bL47/y7pDGm0JNd+YJeYr7Le6wctbYjQ\ngdeIUJg6Ve2arsi+hdIULwqvXHX9oc/Pqsra7zqMVdDs+hgcowAfCUz2v8Y7mwvw\n24iOjfHm/QKBgCuCpOHmSsQdAWmrfSRhVb3y188CKdPiGMilB6K5IvkhuuRZk91r\nzi0T7B3QBPIaWA00S1+esAi0+Q9YpoLx88OsbA0UxSHjJ6onURZHW+ReubPWZhAJ\nAPu1vxMclQMCyKQfdeDyYagCh4BOv36NFec3wgVuL3odHzZA/NaWtOApAoGAWZAb\nQT0Hgc2I7sl16UcWXDjlFAsUSsBhssMJTuZysybXFka97t0a/+odvOE2kFv5g+6n\nhjWOyEBmq39uF7OmTq/PVDFxQngaCbxmBj+w3Bj9bSLsfn3qFlfFwCcASi5DcjZG\nFLNNZET+OR/u4txCCtg8C4baeW0bQOdQJo5jE7UCgYEAm3P4Z/KCNc8CcbF2IJAX\nj6eklvHWXwq3U/ZkizJ4N8khdhVHEtfleUeTBWJWvlG8p2HORz21Yx9QwZouQ92K\ntZq8Lep7lTxkFRzJ92ozKRa/0hfAtYBeCSUyWvBahM9AtwQro4JeF4VUq8iWO784\nslbAEm9kzJhmizdweCZPN1k'] ?? '',
    appId: '1:496830271833:ios:bf3ece156f5d78fe44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    iosBundleId: 'com.example.medtime',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZK78zZubh+xAY\nLfn6e3yri6Kojg+XZFYSrSeb0pdTGpc+nsptg4P6T8cEM3lyVzE9NLY3yZfWiu6S\nrGn1WJ+tMwfbWWfOKadxB9aChVlhSMnBqzN5VyoCYf4NEmUqt4/7sQJ186xl4VCv\nWLVFGWRXEdClgcyZfVFsyqBj7FZG7SrJ4zT5L05PQuEoY5+VjOrs7rERNO/PGDtE\n7bV6/mY3eW8MU8YLVY/ZULITN3XkSXYbEpEJZQjQz8sYWaDLLe5aWgVGOQ2h02P+\nK+BgSXlmJ2YksYkElAcqNBFN3q88OxuBmHQQZKAcqz+wiyZHL+YDO0ee6Xv8g3yC\nl6UT/zs5AgMBAAECggEAD5xLCArWgJUFGqXC6qGfvt8EFKAn3CLUd+JQXVvs4sIc\nxHvL/zXOY1oymw3A9KOIx+dho9VmpW2y611pjiD6Yx1GkXcu8m7B2y30kYhUJ+tS\nbqvLWvREeoowqXXkvCIJqVnsuYc8XITGY5yLmu9/z7Tn2hpctw7z173d81kgoOk+\nHE1WePtLnSUotMvci6T28tdBWeYOGIudTRgOeNNwFCs8rkmXYw1NqmeHDhb2onAR\noH8b+jxziT2RoPRsjTo9Rt3fkdN9AfVQ3QNexuBWYA9pPN+sqJ9ugBMqOYKdfwpz\ntgtZ8XcSXp5J4KFQyqQGsgqrbUdtbZEhMpQ2xqcwRQKBgQDG72XGHrr/Y4FjIxdA\nO1T2ncSGVvSkYPQ503+xJUkWH27yCsqCp7sBksqzveWtVTqbdNkZpcRWh7F+p8VX\nfBn2EsiOCNOTtE2IwDpAOzCb7PaCO/iK3B7NgYg2gGCT38ZmqLO/I3G8tU1iBKPU\n7tO/znGbxoIYTL+okBNH5Q7f7QKBgQDFG7JmoSADNPhpczW6FVV0F22xYFQXUed9\n/Yq9sR0UPb5HjqEHfyKGPOVQ4IFx4nX2bL47/y7pDGm0JNd+YJeYr7Le6wctbYjQ\ngdeIUJg6Ve2arsi+hdIULwqvXHX9oc/Pqsra7zqMVdDs+hgcowAfCUz2v8Y7mwvw\n24iOjfHm/QKBgCuCpOHmSsQdAWmrfSRhVb3y188CKdPiGMilB6K5IvkhuuRZk91r\nzi0T7B3QBPIaWA00S1+esAi0+Q9YpoLx88OsbA0UxSHjJ6onURZHW+ReubPWZhAJ\nAPu1vxMclQMCyKQfdeDyYagCh4BOv36NFec3wgVuL3odHzZA/NaWtOApAoGAWZAb\nQT0Hgc2I7sl16UcWXDjlFAsUSsBhssMJTuZysybXFka97t0a/+odvOE2kFv5g+6n\nhjWOyEBmq39uF7OmTq/PVDFxQngaCbxmBj+w3Bj9bSLsfn3qFlfFwCcASi5DcjZG\nFLNNZET+OR/u4txCCtg8C4baeW0bQOdQJo5jE7UCgYEAm3P4Z/KCNc8CcbF2IJAX\nj6eklvHWXwq3U/ZkizJ4N8khdhVHEtfleUeTBWJWvlG8p2HORz21Yx9QwZouQ92K\ntZq8Lep7lTxkFRzJ92ozKRa/0hfAtYBeCSUyWvBahM9AtwQro4JeF4VUq8iWO784\nslbAEm9kzJhmizdweCZPN1k'] ?? '',
    appId: '1:496830271833:web:89baf939c342664344fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    authDomain: 'medtime-7adda.firebaseapp.com',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    measurementId: 'G-KM8JDQHG5G',
  );
}