// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYld78wl2BFoMaWZ93kRyLwYAuqMFiwVs',
    appId: '1:496830271833:web:5125cde5e96771fc44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    authDomain: 'medtime-7adda.firebaseapp.com',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    measurementId: 'G-DXN8L9K035',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3Lu9YeSwuzW8P7Ak10hIPD00UjiPfg8',
    appId: '1:496830271833:android:053df3ed26945dcc44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYUGXCfJgfUUT12bSyAIPhN5ij7xmMgE',
    appId: '1:496830271833:ios:bf3ece156f5d78fe44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    iosBundleId: 'com.example.medtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYUGXCfJgfUUT12bSyAIPhN5ij7xmMgE',
    appId: '1:496830271833:ios:bf3ece156f5d78fe44fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    iosBundleId: 'com.example.medtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYld78wl2BFoMaWZ93kRyLwYAuqMFiwVs',
    appId: '1:496830271833:web:89baf939c342664344fc48',
    messagingSenderId: '496830271833',
    projectId: 'medtime-7adda',
    authDomain: 'medtime-7adda.firebaseapp.com',
    storageBucket: 'medtime-7adda.firebasestorage.app',
    measurementId: 'G-KM8JDQHG5G',
  );
}
